### ISSUE TITLE
搜尋表單的送出按鈕在高度不夠時無法顯示

### ISSUE THREAD

**Issue by YushengLi** [atitan/coursenote#18]
測試環境

> * 使用瀏覽器：Google Chrome Canary
> * Viewport Width：554 px
> * 放大倍率：100%

當瀏覽器高度不夠高、無法完整顯示表單時，因為表單被 Fixed 完全不能捲動，變成有些欄位、按鈕無法存取，可能需要監聽來設定特定時候才停止捲動...(?)

<img width="960" alt="2015-09-07_16-40-38" src="https://cloud.githubusercontent.com/assets/7748552/9712926/aefef78e-5580-11e5-85b3-9d6f808a9d5f.png">

**Comment by mitour** [comment]
找到更好的表達方法前先暫時這樣寫
