### ISSUE TITLE
scroll bar消失

### ISSUE THREAD

**Issue by atitan** [atitan/coursenote#34]
切到第二頁或後面的頁數，scroll bar會不見

另外，那根太細了

**Comment by mitour** [comment]
搜尋表單的 Affix 在第二頁也會失效，拿掉 application.js 的 /= require turbolinks 兩者都會正常，已試過 jquery-turbolinks 的 gem 但沒用，正在找尋其他解法。

**Comment by atitan** [comment]
把turbolinks拿掉了
